spring.application.name=AITestCaseGenerator

server.port=8080

spring.ai.google.genai.api-key=YOUR_API_KEY

spring.ai.google.genai.chat.options.model=gemini-3.5-flash

spring.ai.google.genai.chat.options.temperature=0.2

spring.thymeleaf.cache=false